/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.bcm.controller;import cn.zhuatech.bcm.common.ApiResponse;import cn.zhuatech.bcm.service.ContinuityExerciseCertificationService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                     */
@RestController @RequestMapping("/api/enterprise/bcm")public class ContinuityExerciseCertificationController{private final ContinuityExerciseCertificationService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                               */
public ContinuityExerciseCertificationController(ContinuityExerciseCertificationService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
@PostMapping("/exercise-certification")public ApiResponse<ContinuityExerciseCertificationService.Assessment>assess(@Valid @RequestBody ContinuityExerciseCertificationService.Request request){return ApiResponse.ok(service.assess(request));}}
