/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.bcm.service;import jakarta.validation.constraints.Min;import jakarta.validation.constraints.NotBlank;import org.springframework.stereotype.Service;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service public class ContinuityExerciseCertificationService{/**
                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                              */
public Assessment assess(Request r){List<String>b=new ArrayList<>(),a=new ArrayList<>();if(!r.criticalProcessesCovered())b.add("关键业务流程未全部覆盖");if(r.actualRecoveryMinutes()>r.rtoMinutes())b.add("实际恢复时间超过 RTO");if(r.actualDataLossMinutes()>r.rpoMinutes())b.add("实际数据丢失超过 RPO");if(!r.dependencyRecoveryVerified())b.add("关键依赖恢复未验证");if(!r.evidenceComplete())b.add("演练证据不完整");if(!b.isEmpty()){a.add("演练不予认证，修复恢复能力后重新演练");return new Assessment(Decision.BLOCKED,b,a);}if(!r.crisisCommunicationTested()||r.openCriticalActions()>0){if(!r.crisisCommunicationTested())a.add("补测危机沟通与联系人树");if(r.openCriticalActions()>0)a.add("关闭关键改进项并验证效果");return new Assessment(Decision.REMEDIATE,b,a);}a.add("认证本次演练并冻结场景、时间线和证据");return new Assessment(Decision.CERTIFY,b,a);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
public record Request(@NotBlank String exerciseId,boolean criticalProcessesCovered,@Min(1)int rtoMinutes,@Min(0)int actualRecoveryMinutes,@Min(0)int rpoMinutes,@Min(0)int actualDataLossMinutes,boolean dependencyRecoveryVerified,boolean crisisCommunicationTested,boolean evidenceComplete,@Min(0)int openCriticalActions){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
public record Assessment(Decision decision,List<String>blockers,List<String>actions){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public enum Decision{CERTIFY,REMEDIATE,BLOCKED}}
