/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.bcm.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                            */
class ContinuityExerciseCertificationServiceTest{private final ContinuityExerciseCertificationService service=new ContinuityExerciseCertificationService();/**
                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                       */
@Test void certifiesSuccessfulExercise(){var r=service.assess(new ContinuityExerciseCertificationService.Request("E1",true,120,90,30,10,true,true,true,0));assertThat(r.decision()).isEqualTo(ContinuityExerciseCertificationService.Decision.CERTIFY);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@Test void blocksRecoveryFailure(){var r=service.assess(new ContinuityExerciseCertificationService.Request("E2",false,60,120,10,30,false,true,false,0));assertThat(r.blockers()).hasSize(5);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
@Test void remediatesCommunicationAndActions(){var r=service.assess(new ContinuityExerciseCertificationService.Request("E3",true,120,90,30,10,true,false,true,2));assertThat(r.actions()).hasSize(2);}}
